- hosts: kubernetes
  collections:
    - kubernetes.core.k8s
  tasks:
  - name: Create a Deployment in Kubernetes cluster
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: spring-petclinic-deployment
          namespace: default
          labels:
            app: spring-petclinic
        spec:
          replicas: 5
          selector:
            matchLabels:
              app: spring-petclinic
          template:
            metadata:
              labels:
                app: spring-petclinic
            spec:
              containers:
              - name: spring-petclinic
                image: "{{ DOCKER_IMAGE_NAME }}:{{BUILD_NUMBER }}"
                ports:
                - containerPort: 8080
                livenessProbe:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 15
                  timeoutSeconds: 1
                  periodSeconds: 10
                resources:
                  requests:
                    cpu: 200m
  - name: Create a Service in Kubernetes cluster    
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('file', 'service.yml') | from_yaml }}"
