- name: Deployment to Kubernetes cluster!
  hosts: tag_Name_kube_control

  collections:
    - kubernetes.core.k8s

  tasks:
    - name: Create a Deployment in Kubernetes cluster
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: spring-petclinic-deployment
            namespace: default
            labels:
              app: spring-petclinic
          spec:
            replicas: 10
            selector:
              matchLabels:
                app: spring-petclinic
            template:
              metadata:
                labels:
                  app: spring-petclinic
              spec:
                containers:
                - name: spring-petclinic
                  image: "{{ DOCKER_IMAGE_NAME }}:{{ BUILD_NUMBER }}"
                  ports:
                  - containerPort: 8080

    - name: Create a Service in Kubernetes cluster    
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Service
          apiVersion: v1
          metadata:
            name: spring-petclinic-service
            namespace: default
          spec:
            type: NodePort
            selector:
              app: spring-petclinic
            ports:
            - protocol: TCP
              port: 8080
              nodePort: 8080
