- hosts: localhost
  collections:
    - kubernetes.core.k8s
  tasks:
  - name: Create a Service
    kubernetes.core.k8s:
      state: present
      definition:
        kind: Service
        apiVersion: v1
        metadata:
          name: spring-petclinic-service
          namespace: default
        spec:
          type: NodePort
          selector:
            app: spring-petclinic
          ports:
          - protocol: TCP
            port: 8080
            nodePort: 8080

  - name: Create a Deployment
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('file', 'deployment.yml') | from_yaml }}"
