---
- name: Install packages!
  hosts: tag_Name_webserver
  become: yes

  tasks:
      - name: Install all necessary apt packages
        apt:
          pkg:
          - python3
          - python3-pip
          - sshpass
          - unzip
          update_cache: yes
          
      - name: Install Ansible and necessary modules
        pip:
          name:
            - ansible
            - openshift
            - boto3