---
plugin: aws_ec2
aws_profile: default
regions:
  - us-west-1
keyed_groups:
  # Add hosts to tag_Name_Value groups for each Name/Value tag pair
  - key: tags.Name
    prefix: tag_Name
    
  - key: tags.Role
    prefix: tag_Role

  - key: tags.Srv
    prefix: tag_Srv

  - key: tags.Project
    prefix: tag_Proj


# filters:
#   # All instances with their tag Role=worker && Role=control
#   tag:Role:
#     - control 
#     - worker
