---
kind: Service
apiVersion: v1
metadata:
  name: spring-petclinic-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: spring-petclinic
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080
