- name: Copy sample files for testing
  become: yes
  copy:
    src: "../files/{{ item }}"
    dest: "/home/{{ ansible_ssh_user }}/{{ item }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0664
  with_items:
    - deployment.yml
    - service.yml