---
- name: Jenkins setup
  hosts: tag_Srv_jenkins
  become: yes

  roles:
     - initial
     - docker
     - ansible
     - geerlingguy.java
     - gantsign.maven
     - geerlingguy.jenkins

- name: Kubernetes cluster setup
  hosts: tag_Srv_kubernetes
  become: yes
  
  roles:
    - initial
    - docker
    - kubernetes