---
- name: Debug 'control-setup.yml'
  hosts: tag_Name_kube_control
  become: yes
  
  # /mnt/ssd/DevOps/EPAM/EPAM.Labs/Final_Project/IaC/roles/kubernetes/files/kube-config.yml
  tasks:

    - name: Copy 'kube-config.yml'
      copy:
        src: /mnt/ssd/DevOps/EPAM/EPAM.Labs/Final_Project/IaC/roles/kubernetes/files/kube-config.yml
        dest: /root

    - name: Initialize a Control node (cluster)
      shell: kubeadm init --config /root/kube-config.yml >> cluster_initialized.txt
      args:
        chdir: /root
        creates: cluster_initialized.txt

    - name: Create .kube directory
      become: yes
      file:
        path: "/home/{{ ansible_ssh_user }}/.kube"
        state: directory
        mode: 0755
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"

    - name: Create a kube config
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_ssh_user }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"

    - name: Setup a Pod network
      become: no
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      

    # Get 'kubeadm join' command and set it as fact to all Worker nodes 
    - name: Get join command on Control node
      become: no
      command: kubeadm token create --print-join-command
      register: join_cmd

    - name: Set 'kubernetes_join_command' to all Worker nodes
      set_fact:
        kubernetes_join_command: "{{ join_cmd.stdout }}"
      when: join_cmd.stdout is defined
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['tag_Role_worker'] }}"
